export const NOTIFICATION_TYPES = {
  NEW_FOLLOWER: 0,
  BOOKMARKED: 1,
  LIKED: 2,
  NEW_REVIEW: 3,
  REVIEW_LIKED: 4,
};

export const NOTIFICATION_NAMES = {
  [NOTIFICATION_TYPES.NEW_FOLLOWER]: 'new follower',
  [NOTIFICATION_TYPES.BOOKMARKED]: 'bookmarked',
  [NOTIFICATION_TYPES.LIKED]: 'liked',
  [NOTIFICATION_TYPES.NEW_REVIEW]: 'new review',
  [NOTIFICATION_TYPES.REVIEW_LIKED]: 'review liked',
};
