export const RECIPES_BY_DIFFICULTY = {
  EASY: 0,
  MEDIUM: 1,
  HARD: 2,
};

export const DIFFICULTY_NAME = {
  [RECIPES_BY_DIFFICULTY.EASY]: 'easy',
  [RECIPES_BY_DIFFICULTY.MEDIUM]: 'medium',
  [RECIPES_BY_DIFFICULTY.HARD]: 'hard',
};

export const RECIPES_BY_TYPE = {
  ME: 0,
  OTHER: 1,
  LIKED: 2,
};

export const RECIPES_BY_CATEGORY = {
  BREAKFAST: 0,
  LUNCH: 1,
  DINNER: 2,
  APPETIZER: 3,
  SALAD: 4,
  SNACK: 5,
  SOUP: 6,
  VEGETARIAN: 7,
  DESSERT: 8,
  DRINKS: 9,
};

export const CATEGORY_NAME = {
  [RECIPES_BY_CATEGORY.BREAKFAST]: 'Breakfast',
  [RECIPES_BY_CATEGORY.LUNCH]: 'Lunch',
  [RECIPES_BY_CATEGORY.DINNER]: 'Dinner',
  [RECIPES_BY_CATEGORY.APPETIZER]: 'Appetizer',
  [RECIPES_BY_CATEGORY.SALAD]: 'Salad',
  [RECIPES_BY_CATEGORY.SNACK]: 'Snack',
  [RECIPES_BY_CATEGORY.SOUP]: 'Soup',
  [RECIPES_BY_CATEGORY.VEGETARIAN]: 'Vegetarian',
  [RECIPES_BY_CATEGORY.DESSERT]: 'Dessert',
  [RECIPES_BY_CATEGORY.DRINKS]: 'Drinks',
};

export const RECIPES_BY_SORT = {
  RECENTLY: 0,
  POPULAR: 1,
  COMMENTED: 2,
  PREPARATION_TIME: 3,
  APPRECIATION: 4,
};

export const SORT_NAME = {
  [RECIPES_BY_SORT.RECENTLY]: 'Recently',
  [RECIPES_BY_SORT.POPULAR]: 'Popular',
  [RECIPES_BY_SORT.COMMENTED]: 'Commented',
  [RECIPES_BY_SORT.PREPARATION_TIME]: 'Preparation Time',
  [RECIPES_BY_SORT.APPRECIATION]: 'Appreciation',
};
